### PR TITLE
chore(design): add CSS scope on co-list

### PR DESCRIPTION
**Pull request by ncoden**
Use angular-pseudo-class to make a "CSS pseudo-classes scope" on `.co-list` : prevent the items inside the list with their own interactions to trigger the list itself. (visual effect only).

Preview:
Preview

### CODE REVIEW

**Comment by iamdey** [comment]
:-1: Changing default browser behaviors is not a good thing.

**Comment by ncoden** [comment]
*CSS itself change the default browser behaviors. CSS is a coat of hack over coats of fixs.*
So I add my fix coat, to improve the CSS events managment ( -> to use the JS events propagation, which can be stopped and triggered, instead of the CSS one)

**Comment by ncoden** [comment]
I really need this branch. And as explain above, it's not dirty at all (not more than CSS itself).
Please reopen

**Comment by iamdey** [comment]
As I explain changing default browser behaviors will impact maintainability and simplicity of the app

**Comment by ncoden** [comment]
It's not changing default browser behaviors, not more EVERYTHING we do in CSS/JS. It's nothing more the control of visual events in JS instead of CSS, while keeping the "pseudo-class" approach precisely for its simplicity.
The component and its parents is still considered as ":hover", nothing is broken. We just change the way the component design will be changed, to have more control on it (like make a child free from its parent design and interactions).

It's simple, maintainable and stable.

*It's dirty, because everything in CSS is dirty*

**Comment by iamdey** [comment]
I rewrite it : please do no change the browser's default event manager.

**Comment by ncoden** [comment]
@iamdey please give arguments, and takes account of my answers

**Pull request closed without merging**
